name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@eceb075b68866911aed3b80d95379713a5a81e5c # 0.9.0
