name: CGL
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare workflow
    uses: eliashaeussler/.github/.github/workflows/pull-request.yaml@main

  cgl:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue == 'true'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2, cs2pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Validation
      - name: Validate composer.json
        run: composer validate --strict

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      # Analyze
      - name: Analyze dependencies
        run: composer analyze:dependencies

      # Linting
      - name: Lint composer.json
        run: composer lint:composer
      - name: Lint Editorconfig
        run: composer lint:editorconfig
      - name: Lint PHP
        run: composer lint:php -- --format checkstyle | cs2pr
      - name: Lint Twig templates
        run: composer lint:twig -- --reporter githubAction
      - name: Lint YAML files
        run: composer lint:yaml -- --format github

      # Schema
      - name: Validate config.yaml against JSON schema
        run: composer validate-schema

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
